import type { SearchRule } from "../services/atuin-cli";

/**
 * How a category is removed, or why it cannot be.
 *
 * `rule` and `verbs` both go through the existing preview → confirm → audit
 * path; nothing here deletes directly. A category with neither is reportable
 * but not purgeable, which is stated rather than hidden: `atuin search` needs
 * a positional query, so a rule expressed purely as a filter (exit code, say)
 * cannot be run at all.
 */
export type Purge =
  | { kind: "rule"; rule: SearchRule }
  | { kind: "verbs"; verbs: string[] }
  | { kind: "dedup" }
  /**
   * Enumerate the distinct commands and delete each by exact match.
   *
   * The escape hatch for categories atuin cannot express as a search — being
   * multi-line is a property of the text, not something a query matches. It
   * costs two CLI invocations per distinct command, so it is slow by
   * construction and the UI says so before starting.
   */
  | { kind: "exact" }
  | { kind: "none"; because: string };

export interface Category {
  id: string;
  label: string;
  /** What the group is, in the user's terms. */
  description: string;
  /** What is lost by removing it — the reason not to, stated up front. */
  cost: string;
  /**
   * SQL predicate over the `history` table, used only to count.
   *
   * The count is indicative. What a purge actually removes is whatever the
   * atuin CLI matches at confirm time, and that number — not this one — is
   * what the confirmation shows.
   */
  predicate: string;
  purge: Purge;
}

/** Commands that are navigation or a glance, not work. */
export const TRIVIAL_VERBS = [
  "ls", "ll", "cat", "echo", "pwd", "clear", "exit", "which", "whoami", "date",
];

/**
 * Categories are ordered by how safe they are to remove, not by size.
 *
 * Agent output first because nothing is lost: those commands were generated by
 * a tool, reference a scratchpad path that no longer exists, and would never be
 * recalled. `cd` is larger but costs directory recall, so it ranks lower.
 */
export const CATEGORIES: Category[] = [
  {
    id: "agent",
    label: "Agent scratchpad",
    description:
      "Commands a coding agent ran through its shell tool. They reference " +
      "/tmp/claude-* paths that no longer exist.",
    cost: "Nothing — these were never typed and cannot be usefully recalled.",
    predicate: "command like '%claude-%' and command like '%/tmp/%'",
    purge: { kind: "rule", rule: { query: "/tmp/claude-", searchMode: "full-text", filterMode: "global" } },
  },
  {
    id: "multiline",
    label: "Multi-line scripts",
    description:
      "Heredocs and pasted scripts — `python3 - <<'EOF'` and similar. Nearly " +
      "all are unique, so they fill the history without ever being recalled.",
    cost:
      "Some: a long script you want back is exactly the kind of thing history " +
      "is for. Check the sample before purging.",
    predicate: "command like '%' || char(10) || '%'",
    purge: { kind: "exact" },
  },
  {
    id: "duplicates",
    label: "Exact duplicates",
    description: "The same command, in the same directory, on the same machine.",
    cost: "Nothing — one copy of each is kept.",
    predicate:
      "rowid not in (select min(rowid) from history where deleted_at is null group by command, cwd, hostname)",
    purge: { kind: "dedup" },
  },
  {
    id: "trivial",
    label: "Trivial lookups",
    description: `${TRIVIAL_VERBS.slice(0, 6).join(", ")} and similar.`,
    cost: "Little — these are faster to retype than to search for.",
    predicate: `substr(command, 1, instr(command || ' ', ' ') - 1) in (${TRIVIAL_VERBS.map((v) => `'${v}'`).join(", ")})`,
    purge: { kind: "verbs", verbs: TRIVIAL_VERBS },
  },
  {
    id: "cd",
    label: "Directory changes",
    description: "Every cd, usually the largest single group.",
    cost:
      "Real: cd history is how you find a path you visited once months ago. " +
      "The biggest win here is also the one most worth keeping.",
    predicate: "(command like 'cd %' or command = 'cd')",
    purge: { kind: "verbs", verbs: ["cd"] },
  },
  {
    id: "interrupted",
    label: "Interrupted (Ctrl-C)",
    description: "Commands you cancelled before they finished.",
    cost: "Some — an interrupted command is often one you meant to fix and rerun.",
    predicate: "exit = 130",
    purge: {
      kind: "none",
      because:
        "atuin search needs a text query; an exit code alone is a filter, not " +
        "something it can match on, so this cannot be purged as a group.",
    },
  },
];
