// GENERATED by scripts/embed-migrations.ts -- do not edit.
// Regenerate with: bun run db:generate
import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };
import m0000SmartBloodaxe from "../../drizzle/0000_smart_bloodaxe.sql" with { type: "text" };
import m0001BlackMaginty from "../../drizzle/0001_black_maginty.sql" with { type: "text" };
import m0002UtcAuditTimestamps from "../../drizzle/0002_utc_audit_timestamps.sql" with { type: "text" };

const files: Record<string, string> = {
  "0000_smart_bloodaxe.sql": m0000SmartBloodaxe,
  "0001_black_maginty.sql": m0001BlackMaginty,
  "0002_utc_audit_timestamps.sql": m0002UtcAuditTimestamps,
};

export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

export const embeddedMigrationCount: number = Object.keys(files).length;
