// GENERATED by scripts/embed-migrations.ts -- do not edit.
// Regenerate with: bun run db:generate
import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };
import m0000SmartBloodaxe from "../../drizzle/0000_smart_bloodaxe.sql" with { type: "text" };

const files: Record<string, string> = {
  "0000_smart_bloodaxe.sql": m0000SmartBloodaxe,
};

export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

export const embeddedMigrationCount: number = Object.keys(files).length;
