/**
 * Generates src/db/migrations-embedded.ts from the drizzle/ folder.
 *
 * A compiled binary is a single file: a relative `migrationsFolder` resolves
 * against the working directory and finds nothing, so the migrator reports
 * "no migrations" and creates no tables at all. Importing the SQL as text
 * compiles it into the binary instead.
 *
 * Fails when the journal and the .sql files disagree in EITHER direction --
 * both mean the binary would ship a manifest that lies about what it can run.
 */
import { readdir } from "node:fs/promises";
import { join } from "node:path";

interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

interface Journal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

const DRIZZLE_DIR = "drizzle";
const OUT_FILE = "src/db/migrations-embedded.ts";

const journalFile = Bun.file(join(DRIZZLE_DIR, "meta", "_journal.json"));
if (!(await journalFile.exists())) {
  console.error(`❌ ${DRIZZLE_DIR}/meta/_journal.json not found.`);
  console.error("💡 Run `bunx drizzle-kit generate` first.");
  process.exit(1);
}

const journal: Journal = await journalFile.json();
const onDisk = (await readdir(DRIZZLE_DIR)).filter((f) => f.endsWith(".sql")).sort();
const inJournal = journal.entries.map((e) => `${e.tag}.sql`);

// Direction 1: journal names a migration that is not on disk.
const missing = inJournal.filter((f) => !onDisk.includes(f));
// Direction 2: a .sql file exists that the journal does not list.
const unlisted = onDisk.filter((f) => !inJournal.includes(f));

if (missing.length || unlisted.length) {
  console.error("❌ drizzle/ and its journal disagree:");
  for (const f of missing) console.error(`   journal lists ${f}, but it is missing on disk`);
  for (const f of unlisted) console.error(`   ${f} is on disk, but absent from the journal`);
  process.exit(1);
}

/** Turns a migration tag into a valid TypeScript identifier. */
function ident(tag: string): string {
  const cleaned = tag.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c: string | undefined) =>
    c ? c.toUpperCase() : ""
  );
  return `m${cleaned.charAt(0).toUpperCase()}${cleaned.slice(1)}`;
}

const imports = journal.entries.map(
  (e) => `import ${ident(e.tag)} from "../../drizzle/${e.tag}.sql" with { type: "text" };`
);
const entries = journal.entries.map((e) => `  "${e.tag}.sql": ${ident(e.tag)},`);

const source = `// GENERATED by scripts/embed-migrations.ts -- do not edit.
// Regenerate with: bun run db:generate
import journalJson from "../../drizzle/meta/_journal.json" with { type: "json" };
${imports.join("\n")}

const files: Record<string, string> = {
${entries.join("\n")}
};

export const embeddedMigrations = {
  journal: JSON.stringify(journalJson),
  files,
};

export const embeddedMigrationCount: number = Object.keys(files).length;
`;

await Bun.write(OUT_FILE, source);
console.log(`✅ Embedded ${journal.entries.length} migration(s) into ${OUT_FILE}`);
for (const e of journal.entries) console.log(`   ${e.tag}.sql`);
